### ISSUE TITLE
Add Typescript

### ISSUE THREAD

**Issue by RodolfoSilva** [chrvadala/kafka-test-helper#1]
Hello @chrvadala , nice work with this lib.

Do you have any plan to add Typescript types?

**Comment by chrvadala** [comment]
Hello @RodolfoSilva, yes I plan to integrate this library with a typedefinition file. Can you help me with a PR?
I'll appreciate a lot!

**Comment by RodolfoSilva** [comment]
Yes, should I rewrite the project in typescript or only add the type definition?

**Comment by chrvadala** [comment]
Thanks for your help. I think that the type definition is enough to have a better autocompletion on our IDEs.
